/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/worker-configuration.d.ts` (hash: 4cf81cfe9b25770647ab755c9b51b533)
interface __BaseEnv_Env {
  GMV_GLOBAL_RATE_LIMITER: RateLimit
  GMV_ORDER_RATE_LIMITER: RateLimit
  GMV_DAILY_AGGREGATE: DurableObjectNamespace<
    import("./worker").CommerceGmvDailyAggregate
  >
  GMV_CUTOVER_FENCE: DurableObjectNamespace<
    import("./worker").CommerceGmvCutoverFence
  >
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker")
    durableNamespaces: "CommerceGmvDailyAggregate" | "CommerceGmvCutoverFence"
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
